sudo: required

services:
  - docker

script:
- docker pull fibjs/fibjs:v0.2.1
- dir=`pwd`; docker run -v ${dir}:/home/app_tmp fibjs/fibjs:v0.2.1 ls -la /home ;cp -rf /home/app_tmp /home/app; cd /home/app; npm install;npm run test;
