language: node_js
node_js: '6'
matrix:
  include:
  {%- for version in versions %}
    - os: linux
      env:
        - VERSION={{version}}
  {%- endfor %}
  {%- for version in versions %}
    - os: osx
      osx_image: xcode9
      env:
        - VERSION={{version}}
  {%- endfor %}

{%- if use_travis_services %}
services:
  {%- for service in travis_services %}
    - {{service}}
  {%- endfor %}
{%- endif %}
before_install:
  - OS=linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.4.0;
      rvm --default use 2.4.0;
      ruby -v;
      brew update;
      brew install xz;
      OS=darwin;
      {%- if use_travis_service__mysql %}
      brew install mariadb;
      mysql.server start;
      {%- endif %}
    fi
  {%- if use_travis_service__mysql %}
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS `fibjs-test`;';
  {%- endif %}
script:
  - npm i
  - mkdir -p ./node_modules/.bin
  - rm -rf ./node_modules/.bin/fibjs
  - curl -SL "https://github.com/fibjs/fibjs/releases/download/v${VERSION}/fibjs-v${VERSION}-${OS}-x64.xz" -o ./node_modules/.bin/fibjs.xz
  - xz -d ./node_modules/.bin/fibjs.xz
  - chmod a+x ./node_modules/.bin/fibjs
  - npm run ci
