addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - curl
language: node_js
node_js: '6'
env:
  {%- for version in versions %}
  - VERSION={{version}}
  {%- endfor %}
script:
  - npm i
  - mkdir -p ./node_modules/.bin
  - curl -SL "https://github.com/fibjs/fibjs/releases/download/v${VERSION}/fibjs-linux-x64" -o ./node_modules/.bin/fibjs
  - chmod a+x ./node_modules/.bin/fibjs
  - npm run ci
